preprocessor: s2t_ctc_var_len
preprocessor_conf:
    na_symbol: "<na>"
    text_prev_apply_prob: 0.0
    lang_apply_prob: 0.5
    nolang_symbol: "<nolang>"

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5

encoder: e_branchformer_ctc
encoder_conf:
    output_size: 256
    attention_heads: 4
    attention_layer_type: selfattn
    pos_enc_layer_type: abs_pos
    rel_pos_type: latest
    cgmlp_linear_units: 1536
    cgmlp_conv_kernel: 31
    use_linear_after_conv: false
    gate_activation: identity
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    layer_drop_rate: 0.0
    linear_units: 2048
    positionwise_layer_type: linear
    use_ffn: true
    macaron_ffn: true
    merge_conv_kernel: 31
    interctc_layer_idx: [6]
    interctc_use_conditioning: true
    use_cross_attention: false
    use_flash_attn: true    # flash attn

promptencoder: transformer
promptencoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 1024
    num_blocks: 0
    use_flash_attn: true

model: espnet_ctc
model_conf:
    interctc_weight: 0.5
    sym_na: "<na>"
    ctc_asr_only: [true, true]  # intermediate + final CTC

optim: adam
optim_conf:
    lr: 0.002
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

batch_type: numel
batch_bins: 250000000
accum_grad: 1
max_epoch: 40
# num_iters_per_epoch: 15000
patience: none
init: none
best_model_criterion:
-   - valid
    - loss_ctc
    - min
-   - valid
    - total_count
    - max
keep_nbest_models: 10
use_amp: true
num_workers: 8
unused_parameters: true
seed: 2024
num_att_plot: 0     # set to 0 due to flash_attn
